name: Check Chrome Web Store credentials

on:
  workflow_dispatch:

jobs:
  check-credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Check Chrome Web Store credentials
        uses: wdzeng/chrome-extension@v2
        with:
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          action: check-credentials